# Generated by Django 2.1.5 on 2023-03-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
